[project]
name = "zhilian-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyttsx3>=2.99",
    "qwen-agent[code-interpreter,gui,mcp,rag]>=0.0.29",
]
